In [25]:
import pandas as pd
total_df = pd.read_csv('/home/zhoulita/scratch/covid_data_unprocessed/dataFrame/tweet_df_loc_1.csv',low_memory=False,lineterminator='\n')
total_df['day_index'] = 1

for i in range(2,351):
    file_dir = '/home/zhoulita/scratch/covid_data_unprocessed/dataFrame/tweet_df_loc_'+str(i)+'.csv'
    temp_df = pd.read_csv(file_dir,lineterminator='\n',low_memory=False)
    temp_df['day_index'] = i
    total_df = pd.concat([total_df,temp_df])
    print(i)

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350

In [26]:
total_df

,Unnamed: 0,created_at,possibly_sensitive,author_id,text,context_annotations,source,id_x,geo_x,public_metrics,...,place_type,id_y,country_code,country,geo_y,name,Lontitude,Latitude,day_index,withheld
0,0,2020-03-19T19:52:19.000Z,False,2306150944,That Indian corona music video is killing me😂,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1240727823830130688,{'place_id': '00e55e2b4c491c5f'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,00e55e2b4c491c5f,NG,Nigeria,"{'type': 'Feature', 'bbox': [7.3045544, 8.9618...",Abuja,7.424094,9.073664,1,NaN
1,1,2020-03-19T20:05:54.000Z,False,801892591285506053,Some of una never stop to de kiss for Cinema? ...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for Android,1240731240719884288,{'place_id': '00e55e2b4c491c5f'},"{'retweet_count': 0, 'reply_count': 2, 'like_c...",...,city,00e55e2b4c491c5f,NG,Nigeria,"{'type': 'Feature', 'bbox': [7.3045544, 8.9618...",Abuja,7.424094,9.073664,1,NaN
2,2,2020-03-19T20:10:49.000Z,False,159033468,Noooo... Its not because of Uncle Corona ooooo...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for Android,1240732480883302400,{'place_id': '00e55e2b4c491c5f'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,00e55e2b4c491c5f,NG,Nigeria,"{'type': 'Feature', 'bbox': [7.3045544, 8.9618...",Abuja,7.424094,9.073664,1,NaN
3,3,2020-03-19T20:11:05.000Z,False,702160979,Religion Still Proving to be Nigeria's greates...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for Android,1240732545186181121,{'place_id': '00e55e2b4c491c5f'},"{'retweet_count': 1, 'reply_count': 2, 'like_c...",...,city,00e55e2b4c491c5f,NG,Nigeria,"{'type': 'Feature', 'bbox': [7.3045544, 8.9618...",Abuja,7.424094,9.073664,1,NaN
4,4,2020-03-19T20:15:07.000Z,False,139432369,The Federal Ministry of Education has ordered ...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for Android,1240733560513925120,{'place_id': '00e55e2b4c491c5f'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,00e55e2b4c491c5f,NG,Nigeria,"{'type': 'Feature', 'bbox': [7.3045544, 8.9618...",Abuja,7.424094,9.073664,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21612,21612,2021-03-04T04:21:51.000Z,False,265090480,Lmaooo y’all not right. https://t.co/2Fl07LxU8z,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1367329416142082052,{'place_id': '4f798ddf05f97f68'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,4f798ddf05f97f68,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-87.798589, 41.69...",Chicago Ridge,-87.778863,41.705400,350,NaN
21613,21613,2021-03-04T04:22:37.000Z,False,500217624,"1,175 new cases\n33 Kentuckians lost\n\n💚💚💚💚💚💚...",NaN,Twitter for iPhone,1367329610212474881,{'place_id': '4bb94133204a9d69'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,4bb94133204a9d69,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-82.738791, 38.40...",Ashland,-82.672376,38.452657,350,NaN
21614,21614,2021-03-04T04:22:52.000Z,False,4583578700,@guwahatiplus You should not take action on th...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for Android,1367329672585826306,{'place_id': '0a750f403270cbb4'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,0a750f403270cbb4,IN,Inde,"{'type': 'Feature', 'bbox': [92.402527, 25.712...",नागांव,92.862467,26.205625,350,NaN
21615,21615,2021-03-04T04:23:12.000Z,False,182962392,These ones they don’t want foreigners ehhh🙆🏾‍♂...,NaN,Twitter for iPhone,1367329755067002881,{'place_id': 'af5141916468f1a7'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,af5141916468f1a7,ZA,South Africa,"{'type': 'Feature', 'bbox': [26.6531735, -28.0...",Welkom,26.728865,-27.951255,350,NaN
21616,21616,2021-03-04T04:23:30.000Z,False,788177535578275842,Have had a few friends recently that have ...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for Android,1367329833592700929,{'place_id': '219082d08e32e8b7'},"{'retweet_count': 0, 'reply_count': 2, 'like_c...",...,city,219082d08e32e8b7,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-72.245537, 42.20...",Warren,-72.209354,42.215666,350,NaN

In [2]:
# total_df.to_csv('/home/zhoulita/scratch/covid_data_unprocessed/dataFrame/tweet_df_loc_total.csv')

In [27]:
#define the boundary for the grid
lower_left_coordinates =[-125.000000,24.000000]
upper_right_coordinates =[-66.000000,50.000000]

filter_df = total_df[(total_df['Lontitude']>=lower_left_coordinates[0])&(total_df['Lontitude']<=upper_right_coordinates[0])&(total_df['Latitude']>=lower_left_coordinates[1])&(total_df['Latitude']<=upper_right_coordinates[1])]
# filter_df.to_csv('/home/zhoulita/scratch/covid_data_unprocessed/dataFrame/tweet_df_loc_us.csv')
filter_df

,Unnamed: 0,created_at,possibly_sensitive,author_id,text,context_annotations,source,id_x,geo_x,public_metrics,...,place_type,id_y,country_code,country,geo_y,name,Lontitude,Latitude,day_index,withheld
38,38,2020-03-19T19:52:30.000Z,False,859271883279159297,fuck corona i miss my boyfriend,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1240727871095631872,{'place_id': 'fbd6d2f5a4e4a15e'},"{'retweet_count': 1, 'reply_count': 0, 'like_c...",...,admin,fbd6d2f5a4e4a15e,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN
39,39,2020-03-19T20:45:44.000Z,False,781285034703491073,@realDonaldTrump is a POS! https://t.co/3AswTG...,"[{'domain': {'id': '10', 'name': 'Person', 'de...",Twitter for iPhone,1240741265064341505,{'place_id': 'fbd6d2f5a4e4a15e'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,admin,fbd6d2f5a4e4a15e,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN
40,40,2020-03-19T21:01:51.000Z,False,2841636924,You know what we all need during this Corona o...,"[{'domain': {'id': '10', 'name': 'Person', 'de...",Twitter for iPhone,1240745322952790016,{'place_id': 'fbd6d2f5a4e4a15e'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,admin,fbd6d2f5a4e4a15e,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN
41,41,2020-03-19T21:33:33.000Z,False,888083561743384576,This corona virus ain’t got shit over the vall...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1240753298140872705,{'place_id': 'fbd6d2f5a4e4a15e'},"{'retweet_count': 0, 'reply_count': 1, 'like_c...",...,admin,fbd6d2f5a4e4a15e,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN
42,42,2020-03-19T21:58:14.000Z,False,2996168750,Corona who? https://t.co/VRJuZvGoaV,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1240759511423397889,"{'place_id': 'fbd6d2f5a4e4a15e', 'coordinates'...","{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,admin,fbd6d2f5a4e4a15e,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,21608,2021-03-04T04:19:57.000Z,False,888393598307323905,Remember that the #MAGA cult both supports and...,"[{'domain': {'id': '10', 'name': 'Person', 'de...",Twitter for iPhone,1367328941128744966,{'place_id': '002c3ee30c95b70f'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,002c3ee30c95b70f,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-95.804153, 30.18...",Magnolia,-95.763763,30.207071,350,NaN
21610,21610,2021-03-04T04:20:38.000Z,False,969234094239264769,"Fast forward one year and you just said “HCW,...","[{'domain': {'id': '10', 'name': 'Person', 'de...",Twitter for iPhone,1367329110914048001,{'place_id': '4337f2014a1d936b'},"{'retweet_count': 2, 'reply_count': 1, 'like_c...",...,city,4337f2014a1d936b,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-117.0723466, 33....",Beaumont,-117.009398,33.935967,350,NaN
21612,21612,2021-03-04T04:21:51.000Z,False,265090480,Lmaooo y’all not right. https://t.co/2Fl07LxU8z,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1367329416142082052,{'place_id': '4f798ddf05f97f68'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,4f798ddf05f97f68,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-87.798589, 41.69...",Chicago Ridge,-87.778863,41.705400,350,NaN
21613,21613,2021-03-04T04:22:37.000Z,False,500217624,"1,175 new cases\n33 Kentuckians lost\n\n💚💚💚💚💚💚...",NaN,Twitter for iPhone,1367329610212474881,{'place_id': '4bb94133204a9d69'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,4bb94133204a9d69,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-82.738791, 38.40...",Ashland,-82.672376,38.452657,350,NaN
21616,21616,2021-03-04T04:23:30.000Z,False,788177535578275842,Have had a few friends recently that have ...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for Android,1367329833592700929,{'place_id': '219082d08e32e8b7'},"{'retweet_count': 0, 'reply_count': 2, 'like_c...",...,city,219082d08e32e8b7,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-72.245537, 42.20...",Warren,-72.209354,42.215666,350,NaN

In [28]:
def get_week_index(df):
    return int((df['day_index']-1)/7)
filter_df['week_index']= filter_df.apply(get_week_index,axis = 1)
filter_df

<ipython-input-28-8ad3877e5249>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filter_df['week_index']= filter_df.apply(get_week_index,axis = 1)

,Unnamed: 0,created_at,possibly_sensitive,author_id,text,context_annotations,source,id_x,geo_x,public_metrics,...,id_y,country_code,country,geo_y,name,Lontitude,Latitude,day_index,withheld,week_index
38,38,2020-03-19T19:52:30.000Z,False,859271883279159297,fuck corona i miss my boyfriend,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1240727871095631872,{'place_id': 'fbd6d2f5a4e4a15e'},"{'retweet_count': 1, 'reply_count': 0, 'like_c...",...,fbd6d2f5a4e4a15e,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN,0
39,39,2020-03-19T20:45:44.000Z,False,781285034703491073,@realDonaldTrump is a POS! https://t.co/3AswTG...,"[{'domain': {'id': '10', 'name': 'Person', 'de...",Twitter for iPhone,1240741265064341505,{'place_id': 'fbd6d2f5a4e4a15e'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,fbd6d2f5a4e4a15e,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN,0
40,40,2020-03-19T21:01:51.000Z,False,2841636924,You know what we all need during this Corona o...,"[{'domain': {'id': '10', 'name': 'Person', 'de...",Twitter for iPhone,1240745322952790016,{'place_id': 'fbd6d2f5a4e4a15e'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,fbd6d2f5a4e4a15e,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN,0
41,41,2020-03-19T21:33:33.000Z,False,888083561743384576,This corona virus ain’t got shit over the vall...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1240753298140872705,{'place_id': 'fbd6d2f5a4e4a15e'},"{'retweet_count': 0, 'reply_count': 1, 'like_c...",...,fbd6d2f5a4e4a15e,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN,0
42,42,2020-03-19T21:58:14.000Z,False,2996168750,Corona who? https://t.co/VRJuZvGoaV,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1240759511423397889,"{'place_id': 'fbd6d2f5a4e4a15e', 'coordinates'...","{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,fbd6d2f5a4e4a15e,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,21608,2021-03-04T04:19:57.000Z,False,888393598307323905,Remember that the #MAGA cult both supports and...,"[{'domain': {'id': '10', 'name': 'Person', 'de...",Twitter for iPhone,1367328941128744966,{'place_id': '002c3ee30c95b70f'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,002c3ee30c95b70f,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-95.804153, 30.18...",Magnolia,-95.763763,30.207071,350,NaN,49
21610,21610,2021-03-04T04:20:38.000Z,False,969234094239264769,"Fast forward one year and you just said “HCW,...","[{'domain': {'id': '10', 'name': 'Person', 'de...",Twitter for iPhone,1367329110914048001,{'place_id': '4337f2014a1d936b'},"{'retweet_count': 2, 'reply_count': 1, 'like_c...",...,4337f2014a1d936b,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-117.0723466, 33....",Beaumont,-117.009398,33.935967,350,NaN,49
21612,21612,2021-03-04T04:21:51.000Z,False,265090480,Lmaooo y’all not right. https://t.co/2Fl07LxU8z,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1367329416142082052,{'place_id': '4f798ddf05f97f68'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,4f798ddf05f97f68,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-87.798589, 41.69...",Chicago Ridge,-87.778863,41.705400,350,NaN,49
21613,21613,2021-03-04T04:22:37.000Z,False,500217624,"1,175 new cases\n33 Kentuckians lost\n\n💚💚💚💚💚💚...",NaN,Twitter for iPhone,1367329610212474881,{'place_id': '4bb94133204a9d69'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,4bb94133204a9d69,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-82.738791, 38.40...",Ashland,-82.672376,38.452657,350,NaN,49
21616,21616,2021-03-04T04:23:30.000Z,False,788177535578275842,Have had a few friends recently that have ...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for Android,1367329833592700929,{'place_id': '219082d08e32e8b7'},"{'retweet_count': 0, 'reply_count': 2, 'like_c...",...,219082d08e32e8b7,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-72.245537, 42.20...",Warren,-72.209354,42.215666,350,NaN,49

In [29]:
#define the grind with the size of m_box * n_box
m_box =70
n_box =35

#use a function to get which place grid box does the tweets belong to
def get_grid_identifier(df):
    x_index = 0
    y_index = 0
    
    x_step = (upper_right_coordinates[0]-lower_left_coordinates[0])/(m_box)
    y_step = (upper_right_coordinates[1]-lower_left_coordinates[1])/(n_box)
    
    while x_index < m_box:
        if lower_left_coordinates[0]+ (x_index+1)* x_step> df['Lontitude']:
            break
        x_index = x_index+1
    
        
    while y_index < n_box:
        if lower_left_coordinates[1]+ (y_index+1)* y_step> df['Latitude']:
            break
        y_index = y_index+1
        
    return str(x_index)+"x"+str(y_index)

filter_df['identifier'] = filter_df.apply(get_grid_identifier,axis = 1)
filter_df

<ipython-input-29-7c0fe3b23621>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filter_df['identifier'] = filter_df.apply(get_grid_identifier,axis = 1)

,Unnamed: 0,created_at,possibly_sensitive,author_id,text,context_annotations,source,id_x,geo_x,public_metrics,...,country_code,country,geo_y,name,Lontitude,Latitude,day_index,withheld,week_index,identifier
38,38,2020-03-19T19:52:30.000Z,False,859271883279159297,fuck corona i miss my boyfriend,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1240727871095631872,{'place_id': 'fbd6d2f5a4e4a15e'},"{'retweet_count': 1, 'reply_count': 0, 'like_c...",...,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN,0,6x17
39,39,2020-03-19T20:45:44.000Z,False,781285034703491073,@realDonaldTrump is a POS! https://t.co/3AswTG...,"[{'domain': {'id': '10', 'name': 'Person', 'de...",Twitter for iPhone,1240741265064341505,{'place_id': 'fbd6d2f5a4e4a15e'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN,0,6x17
40,40,2020-03-19T21:01:51.000Z,False,2841636924,You know what we all need during this Corona o...,"[{'domain': {'id': '10', 'name': 'Person', 'de...",Twitter for iPhone,1240745322952790016,{'place_id': 'fbd6d2f5a4e4a15e'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN,0,6x17
41,41,2020-03-19T21:33:33.000Z,False,888083561743384576,This corona virus ain’t got shit over the vall...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1240753298140872705,{'place_id': 'fbd6d2f5a4e4a15e'},"{'retweet_count': 0, 'reply_count': 1, 'like_c...",...,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN,0,6x17
42,42,2020-03-19T21:58:14.000Z,False,2996168750,Corona who? https://t.co/VRJuZvGoaV,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1240759511423397889,"{'place_id': 'fbd6d2f5a4e4a15e', 'coordinates'...","{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN,0,6x17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,21608,2021-03-04T04:19:57.000Z,False,888393598307323905,Remember that the #MAGA cult both supports and...,"[{'domain': {'id': '10', 'name': 'Person', 'de...",Twitter for iPhone,1367328941128744966,{'place_id': '002c3ee30c95b70f'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-95.804153, 30.18...",Magnolia,-95.763763,30.207071,350,NaN,49,34x8
21610,21610,2021-03-04T04:20:38.000Z,False,969234094239264769,"Fast forward one year and you just said “HCW,...","[{'domain': {'id': '10', 'name': 'Person', 'de...",Twitter for iPhone,1367329110914048001,{'place_id': '4337f2014a1d936b'},"{'retweet_count': 2, 'reply_count': 1, 'like_c...",...,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-117.0723466, 33....",Beaumont,-117.009398,33.935967,350,NaN,49,9x13
21612,21612,2021-03-04T04:21:51.000Z,False,265090480,Lmaooo y’all not right. https://t.co/2Fl07LxU8z,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1367329416142082052,{'place_id': '4f798ddf05f97f68'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-87.798589, 41.69...",Chicago Ridge,-87.778863,41.705400,350,NaN,49,44x23
21613,21613,2021-03-04T04:22:37.000Z,False,500217624,"1,175 new cases\n33 Kentuckians lost\n\n💚💚💚💚💚💚...",NaN,Twitter for iPhone,1367329610212474881,{'place_id': '4bb94133204a9d69'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-82.738791, 38.40...",Ashland,-82.672376,38.452657,350,NaN,49,50x19
21616,21616,2021-03-04T04:23:30.000Z,False,788177535578275842,Have had a few friends recently that have ...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for Android,1367329833592700929,{'place_id': '219082d08e32e8b7'},"{'retweet_count': 0, 'reply_count': 2, 'like_c...",...,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-72.245537, 42.20...",Warren,-72.209354,42.215666,350,NaN,49,62x24

In [80]:
week_data = filter_df[filter_df['week_index'] == 0]
grid_data_week = pd.DataFrame(week_data['identifier'].value_counts())
grid_data_week.reset_index(inplace=True)
grid_data_week.rename(columns={'identifier':'Count'},inplace=True)
grid_data_week['Count'] = grid_data_week['Count']/7
grid_data_week['Week_index'] = 0
grid_data_week

     index       Count  Week_index
0    60x22  331.142857           0
1     7x13  221.142857           0
2     8x13  126.142857           0
3     35x7  124.714286           0
4    49x11   83.000000           0
..     ...         ...         ...
765  31x12    0.142857           0
766  35x31    0.142857           0
767  50x17    0.142857           0
768  38x26    0.142857           0
769   7x29    0.142857           0

[770 rows x 3 columns]

In [81]:
for i in range(1,50):
    week_temp = filter_df[filter_df['week_index'] == i]
    temp = pd.DataFrame(week_temp['identifier'].value_counts())
    temp.reset_index(inplace=True)
    temp.rename(columns={'identifier':'Count'},inplace=True)
    temp['Count'] = temp['Count']/7
    temp['Week_index'] = i
    print(temp.head(5))
    grid_data_week = pd.concat([grid_data_week,temp])

   index       Count  Week_index
0  60x22  285.000000           1
1   7x13  164.857143           1
2   35x7  113.714286           1
3   8x13   96.714286           1
4  49x11   75.571429           1
   index       Count  Week_index
0  60x22  197.428571           2
1   7x13  119.714286           2
2   35x7   75.571429           2
3   8x13   61.857143           2
4  49x11   51.857143           2
   index       Count  Week_index
0  60x22  124.857143           3
1   7x13   70.428571           3
2   35x7   42.285714           3
3   8x13   37.285714           3
4  49x11   32.714286           3
   index       Count  Week_index
0  60x22  468.000000           4
1   7x13  243.285714           4
2  56x20  148.428571           4
3   3x18  127.285714           4
4   8x13  124.000000           4
   index       Count  Week_index
0  60x22  559.714286           5
1   7x13  275.285714           5
2  56x20  185.285714           5
3   3x18  181.428571           5
4  54x26  157.857143           5
   index       Count  Week_index
0  60x22  538.857143           6
1   7x13  262.714286           6
2  56x20  174.714286           6
3   3x18  173.428571           6
4  54x26  156.000000           6
   index       Count  Week_index
0  60x22  518.000000           7
1   7x13  280.142857           7
2  56x20  180.285714           7
3   3x18  175.714286           7
4   8x13  150.285714           7
   index       Count  Week_index
0  60x22  800.428571           8
1   7x13  393.428571           8
2  56x20  274.857143           8
3   3x18  248.714286           8
4   8x13  226.857143           8
   index       Count  Week_index
0  60x22  846.857143           9
1   7x13  404.428571           9
2  54x26  301.571429           9
3  56x20  300.000000           9
4   3x18  252.857143           9
   index       Count  Week_index
0  60x22  695.142857          10
1   7x13  362.714286          10
2  56x20  224.571429          10
3  54x26  191.285714          10
4   3x18  185.000000          10
   index       Count  Week_index
0  60x22  614.000000          11
1   7x13  315.571429          11
2  56x20  209.285714          11
3  54x26  205.714286          11
4   3x18  187.571429          11
   index       Count  Week_index
0  60x22  718.000000          12
1   7x13  434.571429          12
2  56x20  254.142857          12
3  15x12  249.857143          12
4   3x18  241.857143          12
   index       Count  Week_index
0  60x22  830.857143          13
1   7x13  528.714286          13
2   35x7  299.714286          13
3   3x18  282.857143          13
4  56x20  280.857143          13
   index       Count  Week_index
0  60x22  905.000000          14
1   7x13  612.571429          14
2   35x7  367.142857          14
3   3x18  317.142857          14
4   8x13  312.857143          14
   index       Count  Week_index
0  60x22  874.000000          15
1   7x13  553.714286          15
2   3x18  307.428571          15
3  56x20  304.714286          15
4   35x7  290.857143          15
   index       Count  Week_index
0  60x22  835.571429          16
1   7x13  583.000000          16
2   8x13  311.428571          16
3   3x18  311.000000          16
4  56x20  279.285714          16
   index       Count  Week_index
0  60x22  850.285714          17
1   7x13  508.857143          17
2  56x20  300.714286          17
3   3x18  299.714286          17
4   8x13  268.571429          17
   index       Count  Week_index
0  60x22  836.000000          18
1   7x13  506.000000          18
2  56x20  311.285714          18
3   3x18  307.428571          18
4   8x13  250.714286          18
   index       Count  Week_index
0  60x22  845.857143          19
1   7x13  524.428571          19
2  56x20  321.714286          19
3   3x18  295.000000          19
4   8x13  257.857143          19
   index       Count  Week_index
0  60x22  879.000000          20
1   7x13  533.000000          20
2  56x20  308.142857          20
3   3x18  296.571429          20
4  44x24  274.714286          20
   index       Count  Week_index
0  60x22  888.714286          21
1   7x13  542.857143          21
2   3x18  300.571429          21
3  56x20  280.857143          21
4   8x13  246.571429          21
   index       Count  Week_index
0  60x22  809.571429          22
1   7x13  437.714286          22
2   3x18  263.428571          22
3  56x20  227.285714          22
4   8x13  225.428571          22
   index       Count  Week_index
0  60x22  786.142857          23
1   7x13  431.857143          23
2  56x20  264.285714          23
3   3x18  258.000000          23
4  44x24  216.571429          23
   index       Count  Week_index
0  60x22  766.428571          24
1   7x13  438.714286          24
2   3x18  279.714286          24
3  56x20  223.714286          24
4   8x13  221.000000          24
   index       Count  Week_index
0  60x22  828.285714          25
1   7x13  480.714286          25
2   3x18  308.714286          25
3  56x20  269.571429          25
4  54x26  235.428571          25
   index       Count  Week_index
0  60x22  693.285714          26
1   7x13  362.428571          26
2  54x26  267.142857          26
3   3x18  242.142857          26
4  56x20  212.000000          26
   index       Count  Week_index
0  60x22  697.000000          27
1   7x13  343.714286          27
2  54x26  277.000000          27
3   3x18  217.857143          27
4  56x20  209.285714          27
   index        Count  Week_index
0  60x22  1005.142857          28
1   7x13   579.714286          28
2  56x20   363.285714          28
3   3x18   343.714286          28
4   8x13   254.714286          28
   index       Count  Week_index
0  60x22  767.571429          29
1   7x13  440.714286          29
2   3x18  271.857143          29
3  54x26  269.285714          29
4  56x20  268.285714          29
   index       Count  Week_index
0  60x22  639.285714          30
1   7x13  356.142857          30
2   3x18  224.285714          30
3  54x26  222.857143          30
4  56x20  221.714286          30
   index       Count  Week_index
0  60x22  892.000000          31
1   7x13  485.428571          31
2  56x20  315.428571          31
3   3x18  300.714286          31
4  44x24  267.142857          31
   index       Count  Week_index
0  60x22  811.000000          32
1   7x13  473.571429          32
2   3x18  289.285714          32
3  56x20  288.571429          32
4  44x24  257.000000          32
   index       Count  Week_index
0  60x22  976.285714          33
1   7x13  504.000000          33
2  56x20  325.428571          33
3   3x18  307.571429          33
4  44x24  286.428571          33
   index        Count  Week_index
0  60x22  1191.285714          34
1   7x13   609.142857          34
2  56x20   415.857143          34
3   3x18   409.285714          34
4  44x24   394.428571          34
   index        Count  Week_index
0  60x22  1076.428571          35
1   7x13   643.571429          35
2  54x26   427.142857          35
3  56x20   389.428571          35
4   3x18   366.428571          35
   index       Count  Week_index
0  60x22  860.857143          36
1   7x13  480.714286          36
2  54x26  336.857143          36
3  56x20  323.714286          36
4   3x18  296.285714          36
   index        Count  Week_index
0  60x22  1095.142857          37
1   7x13   647.000000          37
2   3x18   416.857143          37
3  56x20   392.285714          37
4   8x13   369.857143          37
   index        Count  Week_index
0  60x22  1141.428571          38
1   7x13   646.142857          38
2   3x18   399.285714          38
3  56x20   382.857143          38
4   8x13   352.428571          38
   index       Count  Week_index
0  60x22  919.142857          39
1   7x13  560.428571          39
2  56x20  359.142857          39
3   3x18  340.857143          39
4   8x13  327.142857          39
   index       Count  Week_index
0  60x22  680.000000          40
1   7x13  458.714286          40
2  54x26  266.428571          40
3   3x18  259.714286          40
4   8x13  254.000000          40
   index       Count  Week_index
0  60x22  712.285714          41
1   7x13  480.428571          41
2  54x26  299.285714          41
3   8x13  261.428571          41
4   3x18  257.571429          41
   index       Count  Week_index
0  60x22  611.285714          42
1   7x13  390.285714          42
2  54x26  302.571429          42
3  56x20  221.714286          42
4   3x18  208.857143          42
   index       Count  Week_index
0  60x22  663.714286          43
1   7x13  428.142857          43
2  54x26  292.428571          43
3  56x20  267.285714          43
4   3x18  252.000000          43
   index       Count  Week_index
0  60x22  694.285714          44
1   7x13  419.857143          44
2  56x20  268.142857          44
3  54x26  257.142857          44
4   3x18  255.571429          44
   index       Count  Week_index
0  60x22  690.285714          45
1   7x13  368.428571          45
2  54x26  251.000000          45
3  56x20  241.142857          45
4   3x18  235.428571          45

   index       Count  Week_index
0  60x22  645.857143          46
1   7x13  317.428571          46
2  54x26  230.714286          46
3   3x18  218.000000          46
4  56x20  215.714286          46
   index       Count  Week_index
0  60x22  551.857143          47
1   7x13  253.000000          47
2  54x26  223.000000          47
3  56x20  196.000000          47
4   3x18  184.428571          47
   index       Count  Week_index
0  60x22  592.142857          48
1   7x13  284.428571          48
2  56x20  227.428571          48
3   3x18  213.142857          48
4  54x26  204.571429          48
   index       Count  Week_index
0  60x22  677.285714          49
1   7x13  347.000000          49
2  56x20  278.857143          49
3   35x7  249.714286          49
4  54x26  247.285714          49

In [83]:
grid_data_week.to_csv('new_processed_avg_data.csv')

331.14285714285717

In [82]:
grid_data_week

     index       Count  Week_index
0    60x22  331.142857           0
1     7x13  221.142857           0
2     8x13  126.142857           0
3     35x7  124.714286           0
4    49x11   83.000000           0
..     ...         ...         ...
905  47x16    0.142857          49
906  14x18    0.142857          49
907  15x34    0.142857          49
908   30x5    0.142857          49
909  36x18    0.142857          49

[45574 rows x 3 columns]