# Preprocess the data toward the average of week for one year using the grid

This notebook is done on ComputeCanada and was used to load all the data of the tweets in the 70*35 grid in US, south of Canada and north of Mexico. The tweets with location id is filtered in to the grid. A table contains the average number of tweets of each gridin different weeks(0-50 week) is generated.

In [ ]:
import pandas as pd
total_df = pd.read_csv('tweet_df_loc_1.csv',low_memory=False,lineterminator='\n')
total_df['day_index'] = 1

for i in range(2,351):
    file_dir = 'tweet_df_loc_'+str(i)+'.csv'
    temp_df = pd.read_csv(file_dir,lineterminator='\n',low_memory=False)
    temp_df['day_index'] = i
    total_df = pd.concat([total_df,temp_df])
    print(i)

In [26]:
total_df

,Unnamed: 0,created_at,possibly_sensitive,author_id,text,context_annotations,source,id_x,geo_x,public_metrics,...,place_type,id_y,country_code,country,geo_y,name,Lontitude,Latitude,day_index,withheld
0,0,2020-03-19T19:52:19.000Z,False,2306150944,That Indian corona music video is killing me😂,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1240727823830130688,{'place_id': '00e55e2b4c491c5f'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,00e55e2b4c491c5f,NG,Nigeria,"{'type': 'Feature', 'bbox': [7.3045544, 8.9618...",Abuja,7.424094,9.073664,1,NaN
1,1,2020-03-19T20:05:54.000Z,False,801892591285506053,Some of una never stop to de kiss for Cinema? ...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for Android,1240731240719884288,{'place_id': '00e55e2b4c491c5f'},"{'retweet_count': 0, 'reply_count': 2, 'like_c...",...,city,00e55e2b4c491c5f,NG,Nigeria,"{'type': 'Feature', 'bbox': [7.3045544, 8.9618...",Abuja,7.424094,9.073664,1,NaN
2,2,2020-03-19T20:10:49.000Z,False,159033468,Noooo... Its not because of Uncle Corona ooooo...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for Android,1240732480883302400,{'place_id': '00e55e2b4c491c5f'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,00e55e2b4c491c5f,NG,Nigeria,"{'type': 'Feature', 'bbox': [7.3045544, 8.9618...",Abuja,7.424094,9.073664,1,NaN
3,3,2020-03-19T20:11:05.000Z,False,702160979,Religion Still Proving to be Nigeria's greates...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for Android,1240732545186181121,{'place_id': '00e55e2b4c491c5f'},"{'retweet_count': 1, 'reply_count': 2, 'like_c...",...,city,00e55e2b4c491c5f,NG,Nigeria,"{'type': 'Feature', 'bbox': [7.3045544, 8.9618...",Abuja,7.424094,9.073664,1,NaN
4,4,2020-03-19T20:15:07.000Z,False,139432369,The Federal Ministry of Education has ordered ...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for Android,1240733560513925120,{'place_id': '00e55e2b4c491c5f'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,00e55e2b4c491c5f,NG,Nigeria,"{'type': 'Feature', 'bbox': [7.3045544, 8.9618...",Abuja,7.424094,9.073664,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21612,21612,2021-03-04T04:21:51.000Z,False,265090480,Lmaooo y’all not right. https://t.co/2Fl07LxU8z,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1367329416142082052,{'place_id': '4f798ddf05f97f68'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,4f798ddf05f97f68,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-87.798589, 41.69...",Chicago Ridge,-87.778863,41.705400,350,NaN
21613,21613,2021-03-04T04:22:37.000Z,False,500217624,"1,175 new cases\n33 Kentuckians lost\n\n💚💚💚💚💚💚...",NaN,Twitter for iPhone,1367329610212474881,{'place_id': '4bb94133204a9d69'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,4bb94133204a9d69,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-82.738791, 38.40...",Ashland,-82.672376,38.452657,350,NaN
21614,21614,2021-03-04T04:22:52.000Z,False,4583578700,@guwahatiplus You should not take action on th...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for Android,1367329672585826306,{'place_id': '0a750f403270cbb4'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,0a750f403270cbb4,IN,Inde,"{'type': 'Feature', 'bbox': [92.402527, 25.712...",नागांव,92.862467,26.205625,350,NaN
21615,21615,2021-03-04T04:23:12.000Z,False,182962392,These ones they don’t want foreigners ehhh🙆🏾‍♂...,NaN,Twitter for iPhone,1367329755067002881,{'place_id': 'af5141916468f1a7'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,af5141916468f1a7,ZA,South Africa,"{'type': 'Feature', 'bbox': [26.6531735, -28.0...",Welkom,26.728865,-27.951255,350,NaN
21616,21616,2021-03-04T04:23:30.000Z,False,788177535578275842,Have had a few friends recently that have ...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for Android,1367329833592700929,{'place_id': '219082d08e32e8b7'},"{'retweet_count': 0, 'reply_count': 2, 'like_c...",...,city,219082d08e32e8b7,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-72.245537, 42.20...",Warren,-72.209354,42.215666,350,NaN

In [2]:
# total_df.to_csv('/home/zhoulita/scratch/covid_data_unprocessed/dataFrame/tweet_df_loc_total.csv')

In [27]:
#define the boundary for the grid
lower_left_coordinates =[-125.000000,24.000000]
upper_right_coordinates =[-66.000000,50.000000]

filter_df = total_df[(total_df['Lontitude']>=lower_left_coordinates[0])&(total_df['Lontitude']<=upper_right_coordinates[0])&(total_df['Latitude']>=lower_left_coordinates[1])&(total_df['Latitude']<=upper_right_coordinates[1])]
# filter_df.to_csv('/home/zhoulita/scratch/covid_data_unprocessed/dataFrame/tweet_df_loc_us.csv')
filter_df

,Unnamed: 0,created_at,possibly_sensitive,author_id,text,context_annotations,source,id_x,geo_x,public_metrics,...,place_type,id_y,country_code,country,geo_y,name,Lontitude,Latitude,day_index,withheld
38,38,2020-03-19T19:52:30.000Z,False,859271883279159297,fuck corona i miss my boyfriend,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1240727871095631872,{'place_id': 'fbd6d2f5a4e4a15e'},"{'retweet_count': 1, 'reply_count': 0, 'like_c...",...,admin,fbd6d2f5a4e4a15e,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN
39,39,2020-03-19T20:45:44.000Z,False,781285034703491073,@realDonaldTrump is a POS! https://t.co/3AswTG...,"[{'domain': {'id': '10', 'name': 'Person', 'de...",Twitter for iPhone,1240741265064341505,{'place_id': 'fbd6d2f5a4e4a15e'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,admin,fbd6d2f5a4e4a15e,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN
40,40,2020-03-19T21:01:51.000Z,False,2841636924,You know what we all need during this Corona o...,"[{'domain': {'id': '10', 'name': 'Person', 'de...",Twitter for iPhone,1240745322952790016,{'place_id': 'fbd6d2f5a4e4a15e'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,admin,fbd6d2f5a4e4a15e,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN
41,41,2020-03-19T21:33:33.000Z,False,888083561743384576,This corona virus ain’t got shit over the vall...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1240753298140872705,{'place_id': 'fbd6d2f5a4e4a15e'},"{'retweet_count': 0, 'reply_count': 1, 'like_c...",...,admin,fbd6d2f5a4e4a15e,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN
42,42,2020-03-19T21:58:14.000Z,False,2996168750,Corona who? https://t.co/VRJuZvGoaV,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1240759511423397889,"{'place_id': 'fbd6d2f5a4e4a15e', 'coordinates'...","{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,admin,fbd6d2f5a4e4a15e,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,21608,2021-03-04T04:19:57.000Z,False,888393598307323905,Remember that the #MAGA cult both supports and...,"[{'domain': {'id': '10', 'name': 'Person', 'de...",Twitter for iPhone,1367328941128744966,{'place_id': '002c3ee30c95b70f'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,002c3ee30c95b70f,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-95.804153, 30.18...",Magnolia,-95.763763,30.207071,350,NaN
21610,21610,2021-03-04T04:20:38.000Z,False,969234094239264769,"Fast forward one year and you just said “HCW,...","[{'domain': {'id': '10', 'name': 'Person', 'de...",Twitter for iPhone,1367329110914048001,{'place_id': '4337f2014a1d936b'},"{'retweet_count': 2, 'reply_count': 1, 'like_c...",...,city,4337f2014a1d936b,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-117.0723466, 33....",Beaumont,-117.009398,33.935967,350,NaN
21612,21612,2021-03-04T04:21:51.000Z,False,265090480,Lmaooo y’all not right. https://t.co/2Fl07LxU8z,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1367329416142082052,{'place_id': '4f798ddf05f97f68'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,4f798ddf05f97f68,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-87.798589, 41.69...",Chicago Ridge,-87.778863,41.705400,350,NaN
21613,21613,2021-03-04T04:22:37.000Z,False,500217624,"1,175 new cases\n33 Kentuckians lost\n\n💚💚💚💚💚💚...",NaN,Twitter for iPhone,1367329610212474881,{'place_id': '4bb94133204a9d69'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,4bb94133204a9d69,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-82.738791, 38.40...",Ashland,-82.672376,38.452657,350,NaN
21616,21616,2021-03-04T04:23:30.000Z,False,788177535578275842,Have had a few friends recently that have ...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for Android,1367329833592700929,{'place_id': '219082d08e32e8b7'},"{'retweet_count': 0, 'reply_count': 2, 'like_c...",...,city,219082d08e32e8b7,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-72.245537, 42.20...",Warren,-72.209354,42.215666,350,NaN

In [28]:
def get_week_index(df):
    return int((df['day_index']-1)/7)
filter_df['week_index']= filter_df.apply(get_week_index,axis = 1)
filter_df

<ipython-input-28-8ad3877e5249>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filter_df['week_index']= filter_df.apply(get_week_index,axis = 1)

,Unnamed: 0,created_at,possibly_sensitive,author_id,text,context_annotations,source,id_x,geo_x,public_metrics,...,id_y,country_code,country,geo_y,name,Lontitude,Latitude,day_index,withheld,week_index
38,38,2020-03-19T19:52:30.000Z,False,859271883279159297,fuck corona i miss my boyfriend,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1240727871095631872,{'place_id': 'fbd6d2f5a4e4a15e'},"{'retweet_count': 1, 'reply_count': 0, 'like_c...",...,fbd6d2f5a4e4a15e,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN,0
39,39,2020-03-19T20:45:44.000Z,False,781285034703491073,@realDonaldTrump is a POS! https://t.co/3AswTG...,"[{'domain': {'id': '10', 'name': 'Person', 'de...",Twitter for iPhone,1240741265064341505,{'place_id': 'fbd6d2f5a4e4a15e'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,fbd6d2f5a4e4a15e,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN,0
40,40,2020-03-19T21:01:51.000Z,False,2841636924,You know what we all need during this Corona o...,"[{'domain': {'id': '10', 'name': 'Person', 'de...",Twitter for iPhone,1240745322952790016,{'place_id': 'fbd6d2f5a4e4a15e'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,fbd6d2f5a4e4a15e,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN,0
41,41,2020-03-19T21:33:33.000Z,False,888083561743384576,This corona virus ain’t got shit over the vall...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1240753298140872705,{'place_id': 'fbd6d2f5a4e4a15e'},"{'retweet_count': 0, 'reply_count': 1, 'like_c...",...,fbd6d2f5a4e4a15e,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN,0
42,42,2020-03-19T21:58:14.000Z,False,2996168750,Corona who? https://t.co/VRJuZvGoaV,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1240759511423397889,"{'place_id': 'fbd6d2f5a4e4a15e', 'coordinates'...","{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,fbd6d2f5a4e4a15e,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,21608,2021-03-04T04:19:57.000Z,False,888393598307323905,Remember that the #MAGA cult both supports and...,"[{'domain': {'id': '10', 'name': 'Person', 'de...",Twitter for iPhone,1367328941128744966,{'place_id': '002c3ee30c95b70f'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,002c3ee30c95b70f,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-95.804153, 30.18...",Magnolia,-95.763763,30.207071,350,NaN,49
21610,21610,2021-03-04T04:20:38.000Z,False,969234094239264769,"Fast forward one year and you just said “HCW,...","[{'domain': {'id': '10', 'name': 'Person', 'de...",Twitter for iPhone,1367329110914048001,{'place_id': '4337f2014a1d936b'},"{'retweet_count': 2, 'reply_count': 1, 'like_c...",...,4337f2014a1d936b,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-117.0723466, 33....",Beaumont,-117.009398,33.935967,350,NaN,49
21612,21612,2021-03-04T04:21:51.000Z,False,265090480,Lmaooo y’all not right. https://t.co/2Fl07LxU8z,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1367329416142082052,{'place_id': '4f798ddf05f97f68'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,4f798ddf05f97f68,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-87.798589, 41.69...",Chicago Ridge,-87.778863,41.705400,350,NaN,49
21613,21613,2021-03-04T04:22:37.000Z,False,500217624,"1,175 new cases\n33 Kentuckians lost\n\n💚💚💚💚💚💚...",NaN,Twitter for iPhone,1367329610212474881,{'place_id': '4bb94133204a9d69'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,4bb94133204a9d69,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-82.738791, 38.40...",Ashland,-82.672376,38.452657,350,NaN,49
21616,21616,2021-03-04T04:23:30.000Z,False,788177535578275842,Have had a few friends recently that have ...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for Android,1367329833592700929,{'place_id': '219082d08e32e8b7'},"{'retweet_count': 0, 'reply_count': 2, 'like_c...",...,219082d08e32e8b7,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-72.245537, 42.20...",Warren,-72.209354,42.215666,350,NaN,49

In [29]:
#define the grind with the size of m_box * n_box
m_box =70
n_box =35

#use a function to get which place grid box does the tweets belong to
def get_grid_identifier(df):
    x_index = 0
    y_index = 0
    
    x_step = (upper_right_coordinates[0]-lower_left_coordinates[0])/(m_box)
    y_step = (upper_right_coordinates[1]-lower_left_coordinates[1])/(n_box)
    
    while x_index < m_box:
        if lower_left_coordinates[0]+ (x_index+1)* x_step> df['Lontitude']:
            break
        x_index = x_index+1
    
        
    while y_index < n_box:
        if lower_left_coordinates[1]+ (y_index+1)* y_step> df['Latitude']:
            break
        y_index = y_index+1
        
    return str(x_index)+"x"+str(y_index)

filter_df['identifier'] = filter_df.apply(get_grid_identifier,axis = 1)
filter_df

<ipython-input-29-7c0fe3b23621>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filter_df['identifier'] = filter_df.apply(get_grid_identifier,axis = 1)

,Unnamed: 0,created_at,possibly_sensitive,author_id,text,context_annotations,source,id_x,geo_x,public_metrics,...,country_code,country,geo_y,name,Lontitude,Latitude,day_index,withheld,week_index,identifier
38,38,2020-03-19T19:52:30.000Z,False,859271883279159297,fuck corona i miss my boyfriend,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1240727871095631872,{'place_id': 'fbd6d2f5a4e4a15e'},"{'retweet_count': 1, 'reply_count': 0, 'like_c...",...,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN,0,6x17
39,39,2020-03-19T20:45:44.000Z,False,781285034703491073,@realDonaldTrump is a POS! https://t.co/3AswTG...,"[{'domain': {'id': '10', 'name': 'Person', 'de...",Twitter for iPhone,1240741265064341505,{'place_id': 'fbd6d2f5a4e4a15e'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN,0,6x17
40,40,2020-03-19T21:01:51.000Z,False,2841636924,You know what we all need during this Corona o...,"[{'domain': {'id': '10', 'name': 'Person', 'de...",Twitter for iPhone,1240745322952790016,{'place_id': 'fbd6d2f5a4e4a15e'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN,0,6x17
41,41,2020-03-19T21:33:33.000Z,False,888083561743384576,This corona virus ain’t got shit over the vall...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1240753298140872705,{'place_id': 'fbd6d2f5a4e4a15e'},"{'retweet_count': 0, 'reply_count': 1, 'like_c...",...,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN,0,6x17
42,42,2020-03-19T21:58:14.000Z,False,2996168750,Corona who? https://t.co/VRJuZvGoaV,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1240759511423397889,"{'place_id': 'fbd6d2f5a4e4a15e', 'coordinates'...","{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-124.482003, 32.5...",California,-119.306607,37.269176,1,NaN,0,6x17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,21608,2021-03-04T04:19:57.000Z,False,888393598307323905,Remember that the #MAGA cult both supports and...,"[{'domain': {'id': '10', 'name': 'Person', 'de...",Twitter for iPhone,1367328941128744966,{'place_id': '002c3ee30c95b70f'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-95.804153, 30.18...",Magnolia,-95.763763,30.207071,350,NaN,49,34x8
21610,21610,2021-03-04T04:20:38.000Z,False,969234094239264769,"Fast forward one year and you just said “HCW,...","[{'domain': {'id': '10', 'name': 'Person', 'de...",Twitter for iPhone,1367329110914048001,{'place_id': '4337f2014a1d936b'},"{'retweet_count': 2, 'reply_count': 1, 'like_c...",...,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-117.0723466, 33....",Beaumont,-117.009398,33.935967,350,NaN,49,9x13
21612,21612,2021-03-04T04:21:51.000Z,False,265090480,Lmaooo y’all not right. https://t.co/2Fl07LxU8z,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1367329416142082052,{'place_id': '4f798ddf05f97f68'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-87.798589, 41.69...",Chicago Ridge,-87.778863,41.705400,350,NaN,49,44x23
21613,21613,2021-03-04T04:22:37.000Z,False,500217624,"1,175 new cases\n33 Kentuckians lost\n\n💚💚💚💚💚💚...",NaN,Twitter for iPhone,1367329610212474881,{'place_id': '4bb94133204a9d69'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-82.738791, 38.40...",Ashland,-82.672376,38.452657,350,NaN,49,50x19
21616,21616,2021-03-04T04:23:30.000Z,False,788177535578275842,Have had a few friends recently that have ...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for Android,1367329833592700929,{'place_id': '219082d08e32e8b7'},"{'retweet_count': 0, 'reply_count': 2, 'like_c...",...,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-72.245537, 42.20...",Warren,-72.209354,42.215666,350,NaN,49,62x24

In [80]:
week_data = filter_df[filter_df['week_index'] == 0]
grid_data_week = pd.DataFrame(week_data['identifier'].value_counts())
grid_data_week.reset_index(inplace=True)
grid_data_week.rename(columns={'identifier':'Count'},inplace=True)
grid_data_week['Count'] = grid_data_week['Count']/7
grid_data_week['Week_index'] = 0
grid_data_week

     index       Count  Week_index
0    60x22  331.142857           0
1     7x13  221.142857           0
2     8x13  126.142857           0
3     35x7  124.714286           0
4    49x11   83.000000           0
..     ...         ...         ...
765  31x12    0.142857           0
766  35x31    0.142857           0
767  50x17    0.142857           0
768  38x26    0.142857           0
769   7x29    0.142857           0

[770 rows x 3 columns]

In [ ]:
for i in range(1,50):
    week_temp = filter_df[filter_df['week_index'] == i]
    temp = pd.DataFrame(week_temp['identifier'].value_counts())
    temp.reset_index(inplace=True)
    temp.rename(columns={'identifier':'Count'},inplace=True)
    temp['Count'] = temp['Count']/7
    temp['Week_index'] = i
    grid_data_week = pd.concat([grid_data_week,temp])

In [83]:
grid_data_week.to_csv('new_processed_avg_data.csv')