# Heat Map on the tweets data

This notebook would visualize the heatmap of all the covid tweets in a daily basis through folium.

In [ ]:
import pandas as pd
total_df = pd.read_csv('/home/zhoulita/john-litao-zhou-file/covid_data_unprocessed/dataFrame/tweet_df_loc_1.csv',low_memory=False,lineterminator='\n')
total_df['day_index'] = 1

for i in range(2,351):
    file_dir = '/home/zhoulita/john-litao-zhou-file/covid_data_unprocessed/dataFrame/tweet_df_loc_'+str(i)+'.csv'
    temp_df = pd.read_csv(file_dir,lineterminator='\n',low_memory=False)
    temp_df['day_index'] = i
    total_df = pd.concat([total_df,temp_df])

In [2]:
total_df

,Unnamed: 0,created_at,possibly_sensitive,author_id,text,context_annotations,source,id_x,geo_x,public_metrics,...,place_type,id_y,country_code,country,geo_y,name,Lontitude,Latitude,day_index,withheld
0,0,2020-03-19T19:52:19.000Z,False,2306150944,That Indian corona music video is killing me😂,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1240727823830130688,{'place_id': '00e55e2b4c491c5f'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,00e55e2b4c491c5f,NG,Nigeria,"{'type': 'Feature', 'bbox': [7.3045544, 8.9618...",Abuja,7.424094,9.073664,1,NaN
1,1,2020-03-19T20:05:54.000Z,False,801892591285506053,Some of una never stop to de kiss for Cinema? ...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for Android,1240731240719884288,{'place_id': '00e55e2b4c491c5f'},"{'retweet_count': 0, 'reply_count': 2, 'like_c...",...,city,00e55e2b4c491c5f,NG,Nigeria,"{'type': 'Feature', 'bbox': [7.3045544, 8.9618...",Abuja,7.424094,9.073664,1,NaN
2,2,2020-03-19T20:10:49.000Z,False,159033468,Noooo... Its not because of Uncle Corona ooooo...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for Android,1240732480883302400,{'place_id': '00e55e2b4c491c5f'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,00e55e2b4c491c5f,NG,Nigeria,"{'type': 'Feature', 'bbox': [7.3045544, 8.9618...",Abuja,7.424094,9.073664,1,NaN
3,3,2020-03-19T20:11:05.000Z,False,702160979,Religion Still Proving to be Nigeria's greates...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for Android,1240732545186181121,{'place_id': '00e55e2b4c491c5f'},"{'retweet_count': 1, 'reply_count': 2, 'like_c...",...,city,00e55e2b4c491c5f,NG,Nigeria,"{'type': 'Feature', 'bbox': [7.3045544, 8.9618...",Abuja,7.424094,9.073664,1,NaN
4,4,2020-03-19T20:15:07.000Z,False,139432369,The Federal Ministry of Education has ordered ...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for Android,1240733560513925120,{'place_id': '00e55e2b4c491c5f'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,00e55e2b4c491c5f,NG,Nigeria,"{'type': 'Feature', 'bbox': [7.3045544, 8.9618...",Abuja,7.424094,9.073664,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21612,21612,2021-03-04T04:21:51.000Z,False,265090480,Lmaooo y’all not right. https://t.co/2Fl07LxU8z,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for iPhone,1367329416142082052,{'place_id': '4f798ddf05f97f68'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,4f798ddf05f97f68,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-87.798589, 41.69...",Chicago Ridge,-87.778863,41.705400,350,NaN
21613,21613,2021-03-04T04:22:37.000Z,False,500217624,"1,175 new cases\n33 Kentuckians lost\n\n💚💚💚💚💚💚...",NaN,Twitter for iPhone,1367329610212474881,{'place_id': '4bb94133204a9d69'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,4bb94133204a9d69,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-82.738791, 38.40...",Ashland,-82.672376,38.452657,350,NaN
21614,21614,2021-03-04T04:22:52.000Z,False,4583578700,@guwahatiplus You should not take action on th...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for Android,1367329672585826306,{'place_id': '0a750f403270cbb4'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,0a750f403270cbb4,IN,Inde,"{'type': 'Feature', 'bbox': [92.402527, 25.712...",नागांव,92.862467,26.205625,350,NaN
21615,21615,2021-03-04T04:23:12.000Z,False,182962392,These ones they don’t want foreigners ehhh🙆🏾‍♂...,NaN,Twitter for iPhone,1367329755067002881,{'place_id': 'af5141916468f1a7'},"{'retweet_count': 0, 'reply_count': 0, 'like_c...",...,city,af5141916468f1a7,ZA,South Africa,"{'type': 'Feature', 'bbox': [26.6531735, -28.0...",Welkom,26.728865,-27.951255,350,NaN
21616,21616,2021-03-04T04:23:30.000Z,False,788177535578275842,Have had a few friends recently that have ...,"[{'domain': {'id': '123', 'name': 'Ongoing New...",Twitter for Android,1367329833592700929,{'place_id': '219082d08e32e8b7'},"{'retweet_count': 0, 'reply_count': 2, 'like_c...",...,city,219082d08e32e8b7,US,Etats-Unis,"{'type': 'Feature', 'bbox': [-72.245537, 42.20...",Warren,-72.209354,42.215666,350,NaN

In [3]:
#define the boundary for the grid
lower_left_coordinates =[-125.000000,24.000000]
upper_right_coordinates =[-66.000000,50.000000]

filter_df = total_df[(total_df['Lontitude']>=lower_left_coordinates[0])&(total_df['Lontitude']<=upper_right_coordinates[0])&(total_df['Latitude']>=lower_left_coordinates[1])&(total_df['Latitude']<=upper_right_coordinates[1])]
filter_df.to_csv('/home/zhoulita/scratch/covid_data_unprocessed/dataFrame/tweet_df_loc_us.csv')

In [ ]:
import folium
from folium.plugins import HeatMapWithTime

#initialize the map and put the data into the map
map_year_heatmap = folium.Map(location=[36.648693, -95.8974445],max_bounds=True, zoom_start=4)

# List comprehension to make out list of lists
heat_data = [[[row['Latitude'],row['Lontitude']] for index, row in total_df[total_df['day_index'] == i].iterrows()] for i in range(1,351)]
# Plot it on the map
hm = HeatMapWithTime(heat_data,auto_play=True,max_opacity=0.8)
hm.add_to(map_year_heatmap)
map_year_heatmap

In [7]:
 map_year_heatmap.save('year_heat_map.html')